server:
  port: 9060
  mode: 'release'
  limitNum: 20
  authentication: 'session'  # 认证方式 jwt， session
  authenticationSave: 'localhost'  # 认证存储 localhost  redis

mysql:
  user: root
  password: '12345678'
  path: '127.0.0.1:3306'
  database: 'bo_test'
  config: 'charset=utf8&parseTime=True&loc=Local'
  logLevel: 0                      # 日志级别  1-Silent、2-Error、3-Warn、4-Info
  maxIdleConns: 10                  # 空闲连接池中连接的最大数量
  maxOpenConns: 100                 # 打开数据库连接的最大数量
  defaultStringSize: 256            # string 类型字段的默认长度
  disableDatetimePrecision: true    # 禁用 datetime 精度，MySQL 5.6 之前的数据库不支持
  dontSupportRenameIndex: false     # 重命名索引时采用删除并新建的方式，MySQL 5.7 之前的数据库和 MariaDB 不支持重命名索引
  dontSupportRenameColumn: false    # 用 `change` 重命名列，MySQL 8 之前的数据库和 MariaDB 不支持重命名列
  skipInitializeWithVersion: false  # 根据当前 MySQL 版本自动配置


redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

session:
  storage: 'localhost'
  key: 'session'
  size: 10
  # 7 * 86400 7天
  maxAge: 604800
  path: '/'
  domain: ''
  httpOnly: true

token:
  secret: "jack"
  issuer: "bo.yang"
  expire: 2   #过期时间以天为单位

redirect:
  url: 'http://www.baidu.com'

log:
  debug: false
  maxAge: 7
  fileName: 'server'
  dirName: 'logs'

