server:
  port: 9060
  mode: 'release'
  limitNum: 20
  authentication: 'session'  # 认证方式 jwt， session
  authenticationSave: 'localhost'  # 认证存储 localhost  redis

mysql:
  user: root
  password: '12345678'
  path: '127.0.0.1:3306'
  database: 'bo_test'
  config: 'charset=utf8&parseTime=True&loc=Local'
  logLevel: 4                       # 日志级别  1-Silent、2-Error、3-Warn、4-Info
  maxIdleConns: 10                  # 空闲连接池中连接的最大数量
  maxOpenConns: 100                 # 打开数据库连接的最大数量

redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

session:
  name: 'sid'
  storage: 'localhost'  # redis localhost
  secret: 'secret222'
  size: 10
  # 7 * 86400 7天
  maxAge: 604800
  path: '/'
  domain: ''
  httpOnly: true

token:
  secret: "secret111"
  issuer: "bo.yang"
  expire: 2   #过期时间以天为单位

redirect:
  url: 'http://www.baidu.com'

log:
  debug: true
  maxAge: 7
  fileName: 'server'
  dirName: 'logs'

